# Pandas

## DataFrame
表形式データのクラス・オブジェクト

<table>
    <tr style='border-bottom:1px black solid'>
        <th></th>
        <th>名前</th>
        <th>年齢</th>
        <th>住所</th>
        <th>血液型</th>
    </tr>
    <tr>
        <td>0</td>
        <td>佐藤</td>
        <td>21</td>
        <td>東京都</td>
        <td>A</td>
    </tr>
    <tr>
        <td>1</td>
        <td>斎藤</td>
        <td>30</td>
        <td>岐阜県</td>
        <td></td>
    </tr>
    <tr>
        <td>2</td>
        <td>鈴木</td>
        <td>18</td>
        <td>埼玉県</td>
        <td>O</td>
    </tr>
    <tr>
        <td>3</td>
        <td>田中</td>
        <td>26</td>
        <td>千葉県</td>
        <td>AB</td>
    </tr>
</table>


## Series
1次元データのクラス・オブジェクト

<table>
    <tr>
        <td>0</td>
        <td>佐藤</td>
    </tr>
    <tr>
        <td>1</td>
        <td>斎藤</td>
    </tr>
    <tr>
        <td>2</td>
        <td>鈴木</td>
    </tr>
    <tr>
        <td>3</td>
        <td>田中</td>
    </tr>
</table>

インデックスの値は，一意な値である必要はない．

In [1]:
import pandas as pd
import numpy as np

## DataFrameの作成

In [2]:
pd.DataFrame(
    {
        '名前':   [  '佐藤',   '斎藤',   '鈴木'],
        '年齢':   [      21,       30,       18],
        '住所':   ['東京都', '岐阜県', '埼玉県'],
        '血液型': [     'A',   np.nan,      'O'],
    }
)

# indexを指定する場合
pd.DataFrame(
    {
        '名前':   [  '佐藤',   '斎藤',   '鈴木'],
        '年齢':   [      21,       30,       18],
        '住所':   ['東京都', '岐阜県', '埼玉県'],
        '血液型': [     'A',   np.nan,      'O'],
    },index=      [   'i-1',    'i-2',    'i-3']
)

     名前  年齢   住所  血液型
i-1  佐藤  21  東京都    A
i-2  斎藤  30  岐阜県  NaN
i-3  鈴木  18  埼玉県    O

## Seriesの作成

In [3]:
pd.Series(
    ['佐藤', '斎藤', '鈴木']
)

# indexを指定する場合
pd.Series(
    ['佐藤', '斎藤', '鈴木'],
    index=['i-1', 'i-2', 'i-3']
)

i-1    佐藤
i-2    斎藤
i-3    鈴木
dtype: object

## ファイル読み込み
以下のファイルを読み込むことができる
- CSV
- Excel
- HTML
- json
- xml
- pickle
など

In [4]:
# 読み込み時にindex扱いする列を指定することも可
poke_df = pd.read_csv('../dataset/pokemon.csv', index_col='id')
display(poke_df)

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability
id,,,,,,,,,,,,,,
1,フシギダネ,bulbasaur,たねポケモン,12,4.0,45,49,49,65,65,45,65,NaN,34.0
2,フシギソウ,ivysaur,たねポケモン,12,4.0,60,62,63,80,80,60,65,NaN,34.0
3,フシギバナ,venusaur,たねポケモン,12,4.0,80,82,83,100,100,80,65,NaN,34.0
4,ヒトカゲ,charmander,とかげポケモン,10,NaN,39,52,43,60,50,65,66,NaN,94.0
5,リザード,charmeleon,かえんポケモン,10,NaN,58,64,58,80,65,80,66,NaN,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10231,ビリリダマ,voltorb-hisui,ボールポケモン,13,12.0,40,30,50,55,55,100,43,9.0,106.0
10232,マルマイン,electrode-hisui,ボールポケモン,13,12.0,60,50,70,80,80,150,43,9.0,106.0
10233,バクフーン,typhlosion-hisui,かざんポケモン,10,8.0,73,84,78,119,85,95,66,NaN,18.0
10234,ハリーセン,qwilfish-hisui,ふうせんポケモン,17,4.0,65,95,85,55,55,85,38,33.0,22.0
10235,ニューラ,sneasel-hisui,かぎづめポケモン,2,4.0,55,95,55,35,75,115,39,51.0,143.0

## DataFrameから行・列を抽出

In [5]:
display(poke_df.loc[:, ['japanese_name']])
display(poke_df.loc[[1], :])
display(poke_df.loc[1 : 3, 'japanese_name' : 'english_name'])

      japanese_name
id
1             フシギダネ
2             フシギソウ
3             フシギバナ
4              ヒトカゲ
5              リザード
...             ...
10231         ビリリダマ
10232         マルマイン
10233         バクフーン
10234         ハリーセン
10235          ニューラ

[1140 rows x 1 columns]

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability
id,,,,,,,,,,,,,,
1,フシギダネ,bulbasaur,たねポケモン,12,4.0,45,49,49,65,65,45,65,NaN,34.0

   japanese_name english_name
id
1          フシギダネ    bulbasaur
2          フシギソウ      ivysaur
3          フシギバナ     venusaur

In [6]:
# Series型で抽出する場合
display(poke_df['japanese_name'])

# DataFrame型で抽出する場合
display(poke_df[['japanese_name']])

id
1        フシギダネ
2        フシギソウ
3        フシギバナ
4         ヒトカゲ
5         リザード
         ...
10231    ビリリダマ
10232    マルマイン
10233    バクフーン
10234    ハリーセン
10235     ニューラ
Name: japanese_name, Length: 1140, dtype: object

      japanese_name
id
1             フシギダネ
2             フシギソウ
3             フシギバナ
4              ヒトカゲ
5              リザード
...             ...
10231         ビリリダマ
10232         マルマイン
10233         バクフーン
10234         ハリーセン
10235          ニューラ

[1140 rows x 1 columns]

## DataFrameの結合

In [7]:
type_df = pd.read_csv('../dataset/pokemon_type.csv', index_col='id')
display(type_df)

   english_name japanese_name
id
1        normal          ノーマル
2      fighting          かくとう
3        flying           ひこう
4        poison            どく
5        ground           じめん
6          rock            いわ
7           bug            むし
8         ghost          ゴースト
9         steel           はがね
10         fire           ほのお
11        water            みず
12        grass            くさ
13     electric           でんき
14      psychic          エスパー
15          ice           こおり
16       dragon          ドラゴン
17         dark            あく
18        fairy         フェアリー

In [8]:
ability_df =  pd.read_csv('../dataset/pokemon_ability.csv', index_col='id')
display(ability_df)

    japanese_name                                        flavor_text
id
1           あくしゅう       臭い　においを　放つことによって\n攻撃した　ときに　相手を\nひるませることが　ある。
2           あめふらし                               登場　したときに\n天気を　雨に　する。
3             かそく                                     毎ターン　素早さが　上がる。
4         カブトアーマー                   硬い　甲羅に　守られて\n相手の　攻撃が\n急所に　当たらない。
5           がんじょう         相手の　技を　受けても\n一撃で　倒されることが　ない。\n一撃必殺技も　効かない。
..            ...                                                ...
263       りゅうのあぎと                              ドラゴンタイプの　技の\n威力が　上がる。
264       しろのいななき                    相手を　倒すと\n冷たい　声で　いなないて\n攻撃が　上がる。
265       くろのいななき                   相手を　倒すと\n恐ろしい　声で　いなないて\n特攻が　上がる。
266       じんばいったい  バドレックスの　きんちょうかんと\nブリザポスの　しろのいななきの\n二つの　特性を　あわせ持つ。
267       じんばいったい  バドレックスの　きんちょうかんと\nレイスポスの　くろのいななきの\n二つの　特性を　あわせ持つ。

[267 rows x 2 columns]

In [9]:
# タイプを記録したDataFrameと結合
poke_df['type1_name'] = poke_df['type1'].map(type_df['japanese_name'])
poke_df['type2_name'] = poke_df['type2'].map(type_df['japanese_name'])

# 特性を記録したDataFrameと結合
poke_df['ability1_name'] = poke_df['ability1'].map(ability_df['japanese_name'])
poke_df['ability2_name'] = poke_df['ability2'].map(ability_df['japanese_name'])
poke_df['hidden-ability_name'] = poke_df['hidden-ability'].map(ability_df['japanese_name'])

display(poke_df)

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability,type1_name,type2_name,ability1_name,ability2_name,hidden-ability_name
id,,,,,,,,,,,,,,,,,,,
1,フシギダネ,bulbasaur,たねポケモン,12,4.0,45,49,49,65,65,45,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
2,フシギソウ,ivysaur,たねポケモン,12,4.0,60,62,63,80,80,60,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
3,フシギバナ,venusaur,たねポケモン,12,4.0,80,82,83,100,100,80,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
4,ヒトカゲ,charmander,とかげポケモン,10,NaN,39,52,43,60,50,65,66,NaN,94.0,ほのお,NaN,もうか,NaN,サンパワー
5,リザード,charmeleon,かえんポケモン,10,NaN,58,64,58,80,65,80,66,NaN,94.0,ほのお,NaN,もうか,NaN,サンパワー
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10231,ビリリダマ,voltorb-hisui,ボールポケモン,13,12.0,40,30,50,55,55,100,43,9.0,106.0,でんき,くさ,ぼうおん,せいでんき,ゆうばく
10232,マルマイン,electrode-hisui,ボールポケモン,13,12.0,60,50,70,80,80,150,43,9.0,106.0,でんき,くさ,ぼうおん,せいでんき,ゆうばく
10233,バクフーン,typhlosion-hisui,かざんポケモン,10,8.0,73,84,78,119,85,95,66,NaN,18.0,ほのお,ゴースト,もうか,NaN,もらいび
10234,ハリーセン,qwilfish-hisui,ふうせんポケモン,17,4.0,65,95,85,55,55,85,38,33.0,22.0,あく,どく,どくのトゲ,すいすい,いかく
10235,ニューラ,sneasel-hisui,かぎづめポケモン,2,4.0,55,95,55,35,75,115,39,51.0,143.0,かくとう,どく,せいしんりょく,するどいめ,どくしゅ

## 抽出条件で操作

In [10]:
# ブールインデックス
poke_df['type1_name']=='くさ'

# ブールインデックスによる抽出
poke_df[poke_df['type1_name']=='くさ']

poke_df[(poke_df['type1_name']=='くさ') & (poke_df['type2_name']=='どく')]

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability,type1_name,type2_name,ability1_name,ability2_name,hidden-ability_name
id,,,,,,,,,,,,,,,,,,,
1,フシギダネ,bulbasaur,たねポケモン,12,4.0,45,49,49,65,65,45,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
2,フシギソウ,ivysaur,たねポケモン,12,4.0,60,62,63,80,80,60,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
3,フシギバナ,venusaur,たねポケモン,12,4.0,80,82,83,100,100,80,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ
43,ナゾノクサ,oddish,ざっそうポケモン,12,4.0,45,50,55,75,65,30,34,NaN,50.0,くさ,どく,ようりょくそ,NaN,にげあし
44,クサイハナ,gloom,ざっそうポケモン,12,4.0,60,65,70,85,75,40,34,NaN,1.0,くさ,どく,ようりょくそ,NaN,あくしゅう
45,ラフレシア,vileplume,フラワーポケモン,12,4.0,75,80,85,110,90,50,34,NaN,27.0,くさ,どく,ようりょくそ,NaN,ほうし
69,マダツボミ,bellsprout,フラワーポケモン,12,4.0,50,75,35,70,30,40,34,NaN,82.0,くさ,どく,ようりょくそ,NaN,くいしんぼう
70,ウツドン,weepinbell,ハエとりポケモン,12,4.0,65,90,50,85,45,55,34,NaN,82.0,くさ,どく,ようりょくそ,NaN,くいしんぼう
71,ウツボット,victreebel,ハエとりポケモン,12,4.0,80,105,65,100,70,70,34,NaN,82.0,くさ,どく,ようりょくそ,NaN,くいしんぼう
315,ロゼリア,roselia,いばらポケモン,12,4.0,50,60,45,100,80,65,30,38.0,102.0,くさ,どく,しぜんかいふく,どくのトゲ,リーフガード
406,スボミー,budew,つぼみポケモン,12,4.0,40,30,35,50,70,55,30,38.0,102.0,くさ,どく,しぜんかいふく,どくのトゲ,リーフガード
407,ロズレイド,roserade,ブーケポケモン,12,4.0,60,70,65,125,105,90,30,38.0,101.0,くさ,どく,しぜんかいふく,どくのトゲ,テクニシャン
590,タマゲタケ,foongus,きのこポケモン,12,4.0,69,55,45,55,55,15,27,NaN,144.0,くさ,どく,ほうし,NaN,さいせいりょく
591,モロバレル,amoonguss,きのこポケモン,12,4.0,114,85,70,85,80,30,27,NaN,144.0,くさ,どく,ほうし,NaN,さいせいりょく
10033,フシギバナ,venusaur-mega,たねポケモン,12,4.0,80,100,123,122,120,80,47,NaN,NaN,くさ,どく,あついしぼう,NaN,NaN
10195,フシギバナ,venusaur-gmax,たねポケモン,12,4.0,80,82,83,100,100,80,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ

## 統計量を調べる
- 平均
- 最大値
- 最小値
- 合計
- 標準偏差
- 分散
- 中央値
- 歪度
- 尖度

In [11]:
max_HP = poke_df['hp'].max()
poke_df[poke_df['hp'] == max_HP]

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability,type1_name,type2_name,ability1_name,ability2_name,hidden-ability_name
id,,,,,,,,,,,,,,,,,,,
242,ハピナス,blissey,しあわせポケモン,1,NaN,255,10,10,75,135,55,30,32.0,131.0,ノーマル,NaN,しぜんかいふく,てんのめぐみ,いやしのこころ
10190,ムゲンダイナ,eternatus-eternamax,キョダイポケモン,4,16.0,255,115,250,125,250,130,46,NaN,NaN,どく,ドラゴン,プレッシャー,NaN,NaN

## 列単位で演算・加工

In [12]:
poke_df['Sum_stats'] = poke_df['hp'] + poke_df['Attack'] + poke_df['Defence'] + poke_df['Special-Attack'] + poke_df['Special-Defence'] + poke_df['Speed']
display(poke_df)

,japanese_name,english_name,genus,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability,type1_name,type2_name,ability1_name,ability2_name,hidden-ability_name,Sum_stats
id,,,,,,,,,,,,,,,,,,,,
1,フシギダネ,bulbasaur,たねポケモン,12,4.0,45,49,49,65,65,45,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ,318
2,フシギソウ,ivysaur,たねポケモン,12,4.0,60,62,63,80,80,60,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ,405
3,フシギバナ,venusaur,たねポケモン,12,4.0,80,82,83,100,100,80,65,NaN,34.0,くさ,どく,しんりょく,NaN,ようりょくそ,525
4,ヒトカゲ,charmander,とかげポケモン,10,NaN,39,52,43,60,50,65,66,NaN,94.0,ほのお,NaN,もうか,NaN,サンパワー,309
5,リザード,charmeleon,かえんポケモン,10,NaN,58,64,58,80,65,80,66,NaN,94.0,ほのお,NaN,もうか,NaN,サンパワー,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10231,ビリリダマ,voltorb-hisui,ボールポケモン,13,12.0,40,30,50,55,55,100,43,9.0,106.0,でんき,くさ,ぼうおん,せいでんき,ゆうばく,330
10232,マルマイン,electrode-hisui,ボールポケモン,13,12.0,60,50,70,80,80,150,43,9.0,106.0,でんき,くさ,ぼうおん,せいでんき,ゆうばく,490
10233,バクフーン,typhlosion-hisui,かざんポケモン,10,8.0,73,84,78,119,85,95,66,NaN,18.0,ほのお,ゴースト,もうか,NaN,もらいび,534
10234,ハリーセン,qwilfish-hisui,ふうせんポケモン,17,4.0,65,95,85,55,55,85,38,33.0,22.0,あく,どく,どくのトゲ,すいすい,いかく,440
10235,ニューラ,sneasel-hisui,かぎづめポケモン,2,4.0,55,95,55,35,75,115,39,51.0,143.0,かくとう,どく,せいしんりょく,するどいめ,どくしゅ,430

In [13]:
poke_df.groupby('japanese_name').mean(numeric_only=True)

,type1,type2,hp,Attack,Defence,Special-Attack,Special-Defence,Speed,ability1,ability2,hidden-ability,Sum_stats
japanese_name,,,,,,,,,,,,
アイアント,7.0,9.0,58.0,109.0,112.0,48.0,48.0,109.0,68.0,55.0,54.0,484.0
アオガラス,3.0,NaN,68.0,67.0,55.0,43.0,55.0,77.0,51.0,127.0,145.0,365.0
アギルダー,7.0,NaN,80.0,70.0,40.0,100.0,60.0,145.0,93.0,60.0,84.0,495.0
アクジキング,17.0,16.0,223.0,101.0,53.0,97.0,53.0,43.0,224.0,NaN,NaN,570.0
アグノム,14.0,NaN,75.0,125.0,70.0,125.0,70.0,115.0,26.0,NaN,NaN,580.0
...,...,...,...,...,...,...,...,...,...,...,...,...
ワニノコ,11.0,NaN,50.0,65.0,64.0,44.0,48.0,43.0,67.0,NaN,125.0,314.0
ワルビアル,5.0,17.0,95.0,117.0,80.0,65.0,70.0,92.0,22.0,153.0,83.0,519.0
ワルビル,5.0,17.0,60.0,82.0,45.0,45.0,45.0,74.0,22.0,153.0,83.0,351.0
ワンパチ,13.0,NaN,59.0,45.0,50.0,40.0,50.0,26.0,237.0,NaN,155.0,270.0
ワンリキー,2.0,NaN,70.0,80.0,50.0,35.0,35.0,35.0,62.0,99.0,80.0,305.0